// Code generated by mockery v2.42.0. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/szaborics/vacations-api/models"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// DeleteVacationByID provides a mock function with given fields: ctx, vacationID
func (_m *Database) DeleteVacationByID(ctx context.Context, vacationID string) (int64, error) {
	ret := _m.Called(ctx, vacationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVacationByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, vacationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, vacationID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vacationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllVacations provides a mock function with given fields: ctx
func (_m *Database) GetAllVacations(ctx context.Context) (*[]models.VacationDAO, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVacations")
	}

	var r0 *[]models.VacationDAO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]models.VacationDAO, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]models.VacationDAO); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.VacationDAO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFilteredVacations provides a mock function with given fields: ctx, filter
func (_m *Database) GetFilteredVacations(ctx context.Context, filter *models.VacationFilter) ([]models.VacationDAO, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredVacations")
	}

	var r0 []models.VacationDAO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) ([]models.VacationDAO, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) []models.VacationDAO); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VacationDAO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.VacationFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacationByID provides a mock function with given fields: ctx, vacationID
func (_m *Database) GetVacationByID(ctx context.Context, vacationID string) (*models.VacationDAO, error) {
	ret := _m.Called(ctx, vacationID)

	if len(ret) == 0 {
		panic("no return value specified for GetVacationByID")
	}

	var r0 *models.VacationDAO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.VacationDAO, error)); ok {
		return rf(ctx, vacationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.VacationDAO); ok {
		r0 = rf(ctx, vacationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.VacationDAO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, vacationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacationCount provides a mock function with given fields: ctx, filter
func (_m *Database) GetVacationCount(ctx context.Context, filter *models.VacationFilter) (int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetVacationCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) (int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) int64); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.VacationFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertVacation provides a mock function with given fields: ctx, vacation
func (_m *Database) InsertVacation(ctx context.Context, vacation models.VacationDAO) (primitive.ObjectID, error) {
	ret := _m.Called(ctx, vacation)

	if len(ret) == 0 {
		panic("no return value specified for InsertVacation")
	}

	var r0 primitive.ObjectID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.VacationDAO) (primitive.ObjectID, error)); ok {
		return rf(ctx, vacation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.VacationDAO) primitive.ObjectID); ok {
		r0 = rf(ctx, vacation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(primitive.ObjectID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.VacationDAO) error); ok {
		r1 = rf(ctx, vacation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
