// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/szaborics/vacations-api/models"
)

// VacationService is an autogenerated mock type for the services.VacationService interface
type VacationService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, filter
func (_m *VacationService) Get(ctx context.Context, filter *models.VacationFilter) ([]models.VacationDTO, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.VacationDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) ([]models.VacationDTO, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.VacationFilter) []models.VacationDTO); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.VacationDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.VacationFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVacationService creates a new instance of VacationService. It also registers a testing interface on the mock and a cleanup function to assert the mock expectations.
// The first argument is typically a *testing.T value.
func NewVacationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacationService {
	mock := &VacationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
